project_id = "bsjjxgpaxfawoyjgufgo"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327

[auth]
enabled = true
port = 54328

[functions.manage-children]
verify_jwt = true

[functions.cartoonify-avatar]
verify_jwt = true

[functions.save-to-library]
verify_jwt = true

[functions.update-settings]
verify_jwt = true

[functions.generate-story-illustration]
verify_jwt = true

[functions.personalize-story-image]
verify_jwt = true

[functions.dalle-face-injection]
verify_jwt = false

[functions.inject-avatar]
verify_jwt = false